name: jalali_date_time
description: A simple JalaliDateTime implementation over dart's DateTime
version: 1.0.0
repository: https://github.com/fmotalleb/global_date_time_dart

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  moti_lints: ^1.0.1
  test: ^1.21.0
dependencies:
  meta: ^1.10.0
