name: hemend_jalali
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/fmotalleb/my_repo

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  moti_lints: ^1.0.1
  test: ^1.21.0
