name: jalali_date_time
description: JalaliDateTime is a Dart package that provides a convenient way to work with Jalali (Persian) dates while using the underlying DateTime structure.
version: 1.0.1
repository: https://github.com/fmotalleb/jalali_date_time_dart

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  moti_lints: ^1.0.1
  test: ^1.21.0
dependencies:
  meta: ^1.10.0
