name: Tests+Merge

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
    semantic_pull_request:
        uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/semantic_pull_request.yml@v1
    build:
      defaults:
        run:
          working-directory: "."
      runs-on: ubuntu-latest
      steps:
        - name: 📚 Git Checkout
          uses: actions/checkout@v4

        - name: 🎯 Setup Dart
          uses: dart-lang/setup-dart@v1
          with:
            sdk: stable

        - name: 📦 Install Dependencies
          run: dart pub get

        - name: ✨ Check Formatting
          run: dart format --line-length 80 --set-exit-if-changed lib

        - name: 🕵️ Analyze
          run: dart analyze --fatal-infos --fatal-warnings lib

        - name: 🧪 Run Tests
          run: |
            dart pub global activate coverage 1.2.0
            dart test -j 4 --coverage=coverage --platform=vm && dart pub global run coverage:format_coverage --lcov ${{(inputs.check_ignore && '--check-ignore') || ''}} --in=coverage --out=coverage/lcov.info --packages=.dart_tool/package_config.json --report-on=lib
            
        - name: Upload coverage reports to Codecov
          uses: codecov/codecov-action@v3
          env: 
            CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          
        - name: 📊 Check Code Coverage
          uses: VeryGoodOpenSource/very_good_coverage@v2
          with:
            path: ./coverage/lcov.info
            exclude: ${{inputs.coverage_excludes}}
            min_coverage: 70
      #   - name: Merge Pull Request
      #     uses: juliangruber/merge-pull-request-action@v1
      #     with:
      #       github-token: ${{ secrets.GITHUB_TOKEN }}
      #       number: 1
      #       method: merge
    autoapprove:
        name: Auto Approve a PR
        runs-on: ubuntu-latest
        needs: build
        steps:
          - name: Auto approve
            uses: hmarr/auto-approve-action@v2.0.0 
            with:
              github-token: ${{ secrets.GITHUB_TOKEN }}
    automerge:
        name: Auto merge after successful checks
        needs: autoapprove
        runs-on: ubuntu-latest
        steps:
          - name: Auto merge
            uses: pascalgn/automerge-action@135f0bdb927d9807b5446f7ca9ecc2c51de03c4a
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              MERGE_METHOD: rebase